now:
	python3 vstore.v1.py
	python3 vstore.v2.py
	python3 vstore.v3.py

p01:
	python3 vstore.v3.py
	python3 lec14.p01.py

p02:
	python3 vstore.v1.py
	python3 lec14.p02.py

base:
	python3 ooclassifierbase.py helpdata.v1
